/*
    SPDX-FileCopyrightText: 2026 Evernight Vista Team <13278297951@sina.cn>
    SPDX-License-Identifier: GPL-3.0-or-later
*/

#include "grubconfigkauthhelper.h"

#include <KAuth/HelperSupport>

#include <KLocalizedString>

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QRegularExpression>
#include <QSaveFile>
#include <QSet>
#include <QStandardPaths>
#include <QStringList>
#include <QTextStream>

#ifndef GRUB_DEFAULT_PATH
#define GRUB_DEFAULT_PATH "/etc/default/grub"
#endif

#ifndef GRUB_DROPIN_PATH
#define GRUB_DROPIN_PATH "/etc/default/grub.d/99_miryu_boot.cfg"
#endif

#ifndef GRUB_CFG_PATH
#define GRUB_CFG_PATH "/boot/grub2/grub.cfg"
#endif

namespace {

QString readTextFile(const QString &path, bool *ok)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        *ok = false;
        return {};
    }

    if (file.size() > 64 * 1024) {
        *ok = false;
        return {};
    }

    *ok = true;
    QTextStream stream(&file);
    return stream.readAll();
}

// -- Parse managed settings from the generated content --

struct ManagedSettings {
    QString timeoutStyle;
    QString timeout;
    bool hasDefault = false;
    QString defaultVal;
    bool hasSaveDefault = false;
    QString saveDefaultVal;
    bool hasCmdline = false;
    QString cmdlineDefault;
};

bool parseManagedSettings(const QString &content, ManagedSettings *settings, QString *error)
{
    if (!content.contains(QStringLiteral("# Generated by Miryu GRUB2 Boot Config"))) {
        *error = i18n("The input file was not generated by Miryu GRUB2 Boot Config.");
        return false;
    }

    const QRegularExpression commentRe(QStringLiteral(R"(^\s*(#.*)?$)"));
    const QRegularExpression styleRe(QStringLiteral(R"(^GRUB_TIMEOUT_STYLE=(menu|hidden)$)"));
    const QRegularExpression timeoutRe(QStringLiteral(R"(^GRUB_TIMEOUT=(-?\d+)$)"));
    const QRegularExpression defaultRe(QStringLiteral(R"(^GRUB_DEFAULT=(saved|\d+)$)"));
    const QRegularExpression saveDefaultRe(QStringLiteral(R"(^GRUB_SAVEDEFAULT=(true|false)$)"));
    const QRegularExpression cmdlineRe(QStringLiteral(R"REX(^GRUB_CMDLINE_LINUX="([A-Za-z0-9_./:=,+@% -]*)"$)REX"));

    bool hasStyle = false;
    bool hasTimeout = false;

    const QStringList lines = content.split(QLatin1Char('\n'));
    for (const QString &rawLine : lines) {
        const QString line = rawLine.trimmed();
        if (commentRe.match(line).hasMatch()) {
            continue;
        }

        auto m = styleRe.match(line);
        if (m.hasMatch()) {
            settings->timeoutStyle = m.captured(1);
            hasStyle = true;
            continue;
        }

        m = timeoutRe.match(line);
        if (m.hasMatch()) {
            const int value = m.captured(1).toInt();
            if (value < -1 || value > 3600) {
                *error = i18n("GRUB_TIMEOUT must be between -1 and 3600.");
                return false;
            }
            settings->timeout = m.captured(1);
            hasTimeout = true;
            continue;
        }

        m = defaultRe.match(line);
        if (m.hasMatch()) {
            settings->hasDefault = true;
            settings->defaultVal = m.captured(1);
            continue;
        }

        m = saveDefaultRe.match(line);
        if (m.hasMatch()) {
            settings->hasSaveDefault = true;
            settings->saveDefaultVal = m.captured(1);
            continue;
        }

        m = cmdlineRe.match(line);
        if (m.hasMatch()) {
            settings->hasCmdline = true;
            settings->cmdlineDefault = m.captured(1);
            continue;
        }

        *error = i18n("Unsupported or unsafe configuration line: %1", line);
        return false;
    }

    if (!hasStyle || !hasTimeout) {
        *error = i18n("The configuration is incomplete.");
        return false;
    }

    return true;
}

// -- Extract old kernel parameters from existing /etc/default/grub --

QString extractOldCmdline(const QString &content)
{
    const QRegularExpression re(QStringLiteral(R"REX(^\s*GRUB_CMDLINE_LINUX\s*=\s*"((?:\\.|[^"\\])*)"\s*$)REX"),
                                QRegularExpression::MultilineOption);
    auto m = re.match(content);
    if (m.hasMatch()) {
        return m.captured(1).trimmed();
    }
    return {};
}

// -- In-place merge of managed settings into /etc/default/grub --

QString mergeIntoGrubFile(const QString &existing, const ManagedSettings &settings)
{
    QStringList lines = existing.split(QLatin1Char('\n'));

    auto updateLine = [&lines](const QString &key, const QString &assignment) {
        const QRegularExpression re(
            QStringLiteral(R"(^\s*%1\s*=.*$)").arg(QRegularExpression::escape(key)));
        for (int i = 0; i < lines.size(); ++i) {
            if (re.match(lines.at(i)).hasMatch()) {
                lines[i] = assignment;
                return;
            }
        }
        lines.append(assignment);
    };

    updateLine(QStringLiteral("GRUB_TIMEOUT_STYLE"),
               QStringLiteral("GRUB_TIMEOUT_STYLE=%1").arg(settings.timeoutStyle));

    updateLine(QStringLiteral("GRUB_TIMEOUT"),
               QStringLiteral("GRUB_TIMEOUT=%1").arg(settings.timeout));

    if (settings.hasDefault) {
        updateLine(QStringLiteral("GRUB_DEFAULT"),
                   QStringLiteral("GRUB_DEFAULT=%1").arg(settings.defaultVal));
    }

    if (settings.hasSaveDefault) {
        updateLine(QStringLiteral("GRUB_SAVEDEFAULT"),
                   QStringLiteral("GRUB_SAVEDEFAULT=%1").arg(settings.saveDefaultVal));
    }

    if (settings.hasCmdline) {
        if (settings.cmdlineDefault.isEmpty()) {
            updateLine(QStringLiteral("GRUB_CMDLINE_LINUX"),
                       QStringLiteral("GRUB_CMDLINE_LINUX=\"\""));
        } else {
            updateLine(QStringLiteral("GRUB_CMDLINE_LINUX"),
                       QStringLiteral("GRUB_CMDLINE_LINUX=\"%1\"").arg(settings.cmdlineDefault));
        }
    }

    QString result = lines.join(QLatin1Char('\n'));
    if (!result.endsWith(QLatin1Char('\n'))) {
        result += QLatin1Char('\n');
    }
    return result;
}

bool writeGrubFile(const QString &content, QString *error)
{
    QSaveFile file(QStringLiteral(GRUB_DEFAULT_PATH));
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        *error = i18n("Could not open %1 for writing.", QStringLiteral(GRUB_DEFAULT_PATH));
        return false;
    }

    file.write(content.toUtf8());
    if (!file.commit()) {
        *error = i18n("Could not atomically replace %1.", QStringLiteral(GRUB_DEFAULT_PATH));
        return false;
    }

    QFile::setPermissions(QStringLiteral(GRUB_DEFAULT_PATH),
                          QFile::ReadOwner | QFile::WriteOwner
                          | QFile::ReadGroup
                          | QFile::ReadOther);
    return true;
}

// -- Remove old drop-in file if present --

void removeOldDropin()
{
    const QString dropinPath = QStringLiteral(GRUB_DROPIN_PATH);
    if (QFile::exists(dropinPath)) {
        if (!QFile::remove(dropinPath)) {
            // Non-fatal: leave a debug message for the application to surface.
        }
    }
}

// -- Update BLS entries via grubby so new kernel parameters take effect --

bool updateBlsEntries(const QString &oldCmdline, const QString &newCmdline, QString *error)
{
    const QString grubbyPath = QStandardPaths::findExecutable(
        QStringLiteral("grubby"), {QStringLiteral("/usr/sbin"), QStringLiteral("/sbin"),
                                   QStringLiteral("/usr/bin"), QStringLiteral("/bin")});

    if (grubbyPath.isEmpty()) {
        return true;
    }

    const QStringList oldParams = oldCmdline.split(QLatin1Char(' '), Qt::SkipEmptyParts);
    const QStringList newParams = newCmdline.split(QLatin1Char(' '), Qt::SkipEmptyParts);

    const QSet<QString> oldSet(oldParams.begin(), oldParams.end());
    const QSet<QString> newSet(newParams.begin(), newParams.end());

    QStringList toAdd;
    for (const auto &p : newSet) {
        if (!oldSet.contains(p)) {
            toAdd << p;
        }
    }

    QStringList toRemove;
    for (const auto &p : oldSet) {
        if (!newSet.contains(p)) {
            toRemove << p;
        }
    }

    if (!toAdd.isEmpty()) {
        QProcess process;
        process.start(grubbyPath,
                      QStringList() << QStringLiteral("--update-kernel=ALL")
                                    << QStringLiteral("--args=%1").arg(toAdd.join(QLatin1Char(' '))));
        if (!process.waitForFinished(60000) || process.exitCode() != 0) {
            *error = i18n("Could not apply new kernel parameters to BLS entries.");
            return false;
        }
    }

    if (!toRemove.isEmpty()) {
        QProcess process;
        process.start(grubbyPath,
                      QStringList() << QStringLiteral("--update-kernel=ALL")
                                    << QStringLiteral("--remove-args=%1").arg(toRemove.join(QLatin1Char(' '))));
        if (!process.waitForFinished(60000) || process.exitCode() != 0) {
            *error = i18n("Could not remove old kernel parameters from BLS entries.");
            return false;
        }
    }

    return true;
}

// -- Regenerate grub.cfg --

QString grubOutputPath()
{
    const QString configured = QStringLiteral(GRUB_CFG_PATH);
    if (QFileInfo::exists(configured)) {
        return configured;
    }

    if (QFileInfo::exists(QStringLiteral("/boot/grub/grub.cfg"))) {
        return QStringLiteral("/boot/grub/grub.cfg");
    }

    return configured;
}

bool regenerateGrub(QString *error)
{
    QProcess process;
    process.start(QStringLiteral("grub2-mkconfig"),
                  QStringList() << QStringLiteral("-o") << grubOutputPath());

    if (!process.waitForFinished(120000)) {
        process.kill();
        process.waitForFinished();
        *error = i18n("grub2-mkconfig timed out.");
        return false;
    }

    if (process.exitStatus() != QProcess::NormalExit || process.exitCode() != 0) {
        const QString stderrText = QString::fromUtf8(process.readAllStandardError()).trimmed();
        *error = stderrText.isEmpty() ? i18n("grub2-mkconfig failed.") : stderrText;
        return false;
    }

    return true;
}

} // namespace

GrubConfigKAuthHelper::GrubConfigKAuthHelper(QObject *parent)
    : QObject(parent)
{
    KLocalizedString::setApplicationDomain("miryu-grub-config");
}

KAuth::ActionReply GrubConfigKAuthHelper::save(const QVariantMap &args)
{
    const QString content = args.value(QStringLiteral("content")).toString();

    ManagedSettings settings;
    QString error;
    if (!parseManagedSettings(content, &settings, &error)) {
        auto reply = KAuth::ActionReply::HelperErrorReply();
        reply.setErrorDescription(error);
        return reply;
    }

    // Read existing /etc/default/grub
    QString existingContent;
    bool grubExists = false;
    {
        bool readOk = false;
        existingContent = readTextFile(QStringLiteral(GRUB_DEFAULT_PATH), &readOk);
        grubExists = readOk && !existingContent.isEmpty();
    }

    // Extract old cmdline for grubby diff update
    const QString oldCmdline = grubExists ? extractOldCmdline(existingContent) : QString();

    // Merge managed settings into /etc/default/grub
    const QString mergedContent = mergeIntoGrubFile(grubExists ? existingContent : QString(), settings);

    if (!writeGrubFile(mergedContent, &error)) {
        auto reply = KAuth::ActionReply::HelperErrorReply();
        reply.setErrorDescription(error);
        return reply;
    }

    // Clean up old drop-in file if present
    removeOldDropin();

    // Update BLS entries via grubby (non-fatal on failure)
    const QString newCmdline = settings.hasCmdline ? settings.cmdlineDefault : QString();
    if (!updateBlsEntries(oldCmdline, newCmdline, &error)) {
        // Non-fatal: continue to grub2-mkconfig
    }

    // Regenerate grub.cfg
    if (!regenerateGrub(&error)) {
        auto reply = KAuth::ActionReply::HelperErrorReply();
        reply.setErrorDescription(error);
        return reply;
    }

    auto reply = KAuth::ActionReply::SuccessReply();
    reply.addData(QStringLiteral("message"), i18n("GRUB2 configuration updated."));
    return reply;
}

KAUTH_HELPER_MAIN("org.miryugaming.grubconfig", GrubConfigKAuthHelper)
